flask-practice/blog/user/models.py
from blog import db
from werkzeug.security import check_password_hash, generate_password_hash
from flask_login import UserMixin


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(20))
    username = db.Column(db.String(20))
    password = db.Column(db.String(200))

    def __init__(self, name: str, user_name: str, password: str):
        self.name = name
        self.username = user_name
        self.password = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password, password)

flask-practice/blog/user/forms.py
from flask_wtf import FlaskForm
from wtforms.validators import DataRequired, EqualTo, ValidationError
from wtforms import StringField, SubmitField, PasswordField
from .dao import user_dao


class RegistrationForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    password2 = PasswordField('Repeat Password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Register')

    def validate_username(self, username):
        if user_dao.check_user_exists(username=username):
            raise ValidationError('User is already registered. Please use a different username.')


class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Save')

flask-practice/blog/__init__.py
from flask import Flask
from .config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager


db = SQLAlchemy()
migrate = Migrate()
login = LoginManager()


def create_app():
    app = Flask(__name__)

    app.config.from_object(Config)
    db.init_app(app)
    migrate.init_app(app=app, db=db)

    login.init_app(app=app)
    login.login_view = 'user.login'

    from blog.api import api_blueprint
    from .views import root_blueprint
    from .home.views import home_blueprint
    from .user.views import user_blueprint
    from .person.views import person_blueprint

    app.register_blueprint(api_blueprint)
    app.register_blueprint(root_blueprint)
    app.register_blueprint(home_blueprint)
    app.register_blueprint(user_blueprint)
    app.register_blueprint(person_blueprint)

    return app

from blog import views

flask-practice/blog/api/__init__.py
from flask.blueprints import Blueprint


api_blueprint = Blueprint('api', __name__)


from blog.api import users

flask-practice/blog/home/views.py
from flask.blueprints import Blueprint
from flask import render_template


home_blueprint = Blueprint('home', __name__, template_folder='templates')


@home_blueprint.route('/home')
def home():
    return render_template('home.html')

flask-practice/blog/person/views.py
from flask.blueprints import Blueprint
from flask import render_template


person_blueprint = Blueprint('person', __name__, template_folder='templates')


@person_blueprint.route("/person")
def home():
    persons = ['Samskriti', 'Sabhyata']
    return render_template('home.html', users = persons)

flask-practice/blog/user/views.py
from flask.blueprints import Blueprint
from flask import render_template, redirect, url_for, request
from .dao import user_dao
from blog.user.forms import RegistrationForm, LoginForm
from flask_login import current_user, login_user, logout_user, login_required
from werkzeug.urls import url_parse


user_blueprint = Blueprint('user', __name__, template_folder='templates')


@user_blueprint.route("/register", methods = ['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('user.user_logged_in'))
    
    form = RegistrationForm()

    if form.validate_on_submit():
        user_dao.register_user(form.name.data, form.username.data, form.password.data)
        return redirect(url_for('user.user_registered'))
    
    return render_template('user_registration.html', form=form)

@user_blueprint.route("/login", methods = ['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('user.user_logged_in'))
    
    form = LoginForm()

    if form.validate_on_submit():
        user = user_dao.get_user(form.username.data)

        if not user or not user.verify_password(form.password.data):
            return redirect(url_for('user.login'))
         
        login_user(user=user)
        next_page = request.args.get('next')
        
        if not next_page or url_parse(next_page).netloc != '':
            next_page = url_for('user.login')
        
        return redirect(url_for('user.user_logged_in'))

    return render_template('user_login.html', form=form)

@user_blueprint.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('user.login'))


@user_blueprint.route("/user_created")
@login_required
def user_registered():
    return render_template('user_registered.html')

@user_blueprint.route("/user_logged_in")
@login_required
def user_logged_in():
    return render_template('post_login.html')

@user_blueprint.route("/list_users")
def list_users():
    users = user_dao.get_all_users()
    return render_template('list_users.html', users = users)

flask-practice/blog/views.py
from flask import render_template
from flask.blueprints import Blueprint


root_blueprint = Blueprint('root', __name__)
@root_blueprint.route("/")
def root():
    return render_template('index.html')

flask-practice/blog/templates/base.html
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]>      <html class="no-js"> <!--<![endif]-->
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>Flask Django Practice</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    </head>
    <body>
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
              <a class="navbar-brand" href="{{ url_for('root.root') }}">Root</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{ url_for('home.home') }}">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="#">User</a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Dropdown
                    </a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="{{ url_for('user.register')}}">Register</a></li>
                      {% if current_user.is_anonymous %}
                        <li><a class="dropdown-item" href="{{ url_for('user.login')}}">Login</a></li>
                      {% else %}                    
                      <li><a class="dropdown-item" href="{{ url_for('user.logout')}}">Logout</a></li>
                      {% endif %}
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="{{ url_for('user.list_users')}}">List Users</a></li>
                    </ul>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link disabled">Disabled</a>
                  </li>
                </ul>
                <form class="d-flex" role="search">
                  <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
              </div>
            </div>
          </nav>
        
        {% block content %}
        {% endblock %}
        
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    </body>
</html>

flask-practice/blog/templates/index.html
{% extends 'base.html' %}
{% block content %}
<h1>
    This is main home page.
</h1>
{% endblock %}